name: vertx-hazelcast (4.x)
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  CI:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 8
    uses: ./.github/workflows/ci.yml
    with:
      branch: 4.x
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
    secrets: inherit
  IT:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 8
    uses: ./.github/workflows/it.yml
    with:
      branch: 4.x
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
    secrets: inherit
  Deploy:
    if: ${{ github.repository_owner == 'vert-x3' && (github.event_name == 'push' || github.event_name == 'schedule') }}
    needs: [CI, IT]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: 4.x
      jdk: 8
    secrets: inherit
