name: vertx-hazelcast (4.x)
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [8,11]
        hz: [4.2.8,5.3.2]
        exclude:
          - jdk: 8
            hz: 5.3.2
    uses: ./.github/workflows/ci.yml
    with:
      branch: 4.x
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      hz: ${{ matrix.hz }}
    secrets: inherit
  IT:
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [8,11]
        hz: [4.2.8,5.3.2]
        exclude:
          - jdk: 8
            hz: 5.3.2
    uses: ./.github/workflows/it.yml
    with:
      branch: 4.x
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      hz: ${{ matrix.hz }}
    secrets: inherit
  Deploy:
    if: ${{ github.repository_owner == 'vert-x3' && (github.event_name == 'push' || github.event_name == 'schedule') }}
    needs: [CI, IT]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: 4.x
      jdk: 8
    secrets: inherit
