name: CI matrix (5.x)
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
jobs:
  CI:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 21 ]
        hz: [  5.4.0, 5.5.0 ]
        include:
          - os: ubuntu-latest
            jdk: 11
            hz: 5.3.8
          - os: ubuntu-latest
            jdk: 11
            hz: 5.3.8
            profile: '-Ptest-jpms'
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ inputs.branch }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      hz: ${{ matrix.hz }}
      profile: ${{ matrix.profile }}
    secrets: inherit
  IT:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 21 ]
        hz: [ 5.4.0, 5.5.0 ]
        include:
          - os: ubuntu-latest
            jdk: 11
            hz: 5.3.8
    uses: ./.github/workflows/it.yml
    with:
      branch: ${{ inputs.branch }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      hz: ${{ matrix.hz }}
    secrets: inherit
  Deploy:
    if: ${{ github.repository_owner == 'vert-x3' && (github.event_name == 'push' || github.event_name == 'schedule') }}
    needs: [CI, IT]
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.event.pull_request.head.sha || github.ref_name }}
      jdk: 11
    secrets: inherit
